# Generated by Django 4.2.3 on 2023-09-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='in_available',
            new_name='is_available',
        ),
    ]
