# Generated by Django 4.2.3 on 2023-08-18 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernamae',
            new_name='username',
        ),
    ]
